server:
  port: 9090
  servlet:
    session:
      timeout: 14400
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb
    username: root
    password: root
    druid:
      initial-size: 5 # 初始化连接池大小
      min-idle: 10 # 最小维持的连接池大小
      max-active: 50 # 最大可提供的连接数量
      max-wait: 60000 # 最长等待时间
      time-between-eviction-runs-millis: 6000 # 关闭空闲连接间隔（毫秒）
      min-evictable-idle-time-millis: 30000 # 连接最小的生存时间
      validation-query: SELECT 1 FROM dual # 数据库的状态检测
      test-while-idle: true # 判断连接是否可用
      test-on-borrow: false # 在获得连接之前是否要进行测试
      test-on-return: false # 归还连接前是否需要进行测试
      pool-prepared-statements: false # 不缓存PSTMT
      max-pool-prepared-statement-per-connection-size: 20 # 配置PSTMT缓存个数
  redis:
    host: 47.96.17.2
    port: 6379
    database: 0
  mail:
    host: smtp.qq.com
    username: 3100366252@qq.com
    password: ztuvxkgkuzbvdffc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
mybatis-plus:
  type-aliases-package: com.huashan.yebserver.domain
  mapper-locations: classpath:mapper/yebserver/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt: data :这个路径是根据JWTUtil中的
#@ConfigurationProperties("jwt.data")配置的
jwt:
  data:
    #    jwt加密密钥
    SECRET: json-web-token
    #    jwt储存的请求头Authorization固定写法
    tokenHeader: Authorization
    #      jwt的过期时间(60s*60min*24h*7day)
    expiration: 604800
    #    jwt负载中拿到的头信息
    tokenHead: Bearer
phz:
  oss:
    access-key-secret: mlNSMdBnwH5hLbIRJS0u6LtoCLklTH
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucket-name: phztest
    access-key-id: LTAI5tMjKTTVgGLHSFLoiKk7